config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'adminsdir', controllers: {
    registrations: "adminsdir/v1/admins/registrations",
    sessions: "adminsdir/v1/admins/sessions"
    }, path_names: { sign_in: :login }

  devise_scope :admin do
    post 'adminsdir/add_admin' => "adminsdir/v1/admins/registrations#add_admin", as: :adminsdir_v1_admins_new_admin
  end  
  
  devise_for :users, path: '' , controllers: {
    registrations: "usersdir/v1/users/registrations",
    sessions: "usersdir/v1/users/sessions"
    }, path_names: { sign_up: :register }

  authenticated :admin do
    root "adminsdir/v1/admins/admins#index", as: :admin_authenticated_root
  end

  authenticated :user do
    root 'usersdir/v1/users/users#index', as: :authenticated_root
  end
  namespace :adminsdir do
    namespace :v1, path: '' do
      namespace :admins, path: '' do
        get 'add_admin' => "admins#new_admin"
        root 'admins#index'
        resources :users
        get 'change_status' => "users#change_status"
        get 'admin_change_status' => "admins#change_status"
        get "profile" => "admins#profile"
        post 'update_details' => "admins#update_details"
        patch 'update_password' => "admins#update_password"
        resources :admins

      end
    end
  end
  post 'new_card' => 'usersdir/v1/users/cards#add_new_card'
  patch 'update_password' => "usersdir/v1/users/users"
  post 'update_subscription' => "usersdir/v1/users/users#update_subscription"
  namespace :usersdir, path: '' do
    namespace :v1, path: '' do
      namespace :users, path: '' do
        get 'profile/:id' => 'users#show'
        post 'edit' => 'users#update_details'
        post 'exports' => 'users#exports'
        get 'exports' => 'users#exports'
        post 'filter_export' => 'users#filter_export'
        post 'clear_patches' => "users#clear_patches"
        resources :users, except: [:show] do
          get 'payments' => 'cards#new'
          resources :cards, except: [:new]
        end
      end
    end
  end

  
  get 'addpin' => 'welcome#addpin'
  get 'test' => 'welcome#stripetest'
  get 'pricing' => 'welcome#pricing'

  root 'welcome#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_create :generate_customer_id
  has_many :cards
  has_many :patches
  has_many :searches
  has_many :business_searches
 private
	def generate_customer_id
		customer = Stripe::Customer.create(:email => self.email)
		self.customer_id = customer.id
		self.save
	end
end

app/controllers/adminsdir/v1/admins/users_controller.rb
class Adminsdir::V1::Admins::UsersController < ApplicationController
	layout 'admin'
	before_action :log_in
	def index
		
	end
	def show
		@user = User.find params[:id]
		@role = Role.find @user.role_id
	end
	def change_status
		if !params[:status].nil?
			@user = User.find params[:id]
			@user.is_active = params[:status]
			@user.save
		end

		if !params[:index].nil?
			redirect_to adminsdir_v1_admins_root_path
		else
			redirect_to adminsdir_v1_admins_user_path(@user.id)
		end
	end
	private
	  def log_in
	  	if !admin_signed_in?
	  		redirect_to new_admin_session_path
	  	end
	  end
end

app/controllers/usersdir/v1/users/cards_controller.rb
class Usersdir::V1::Users::CardsController < ApplicationController
	layout "users"
	def new
		@card = Card.new
	end
	def create
		begin
			customer = Stripe::Customer.retrieve(current_user.customer_id)
			sources = customer.sources.create(source: params[:stripe_token] )
			if customer
				card = Card.create( stripe_id: params[:stripe_token], user_id: current_user.id, last_4: sources.last4, fingerprint: sources.fingerprint, brand: sources.brand, exp_month: sources.exp_month, exp_year: sources.exp_year, is_active: 1, card_name: sources.name )
				if card
					@role = Role.find_by_number(current_user.subscription)
					@subscription = Stripe::Subscription.create(
					  :customer => current_user.customer_id,
					  :items => [
					    {
					      :plan => @role.number,
					    }
					  ]
					)
					current_user.is_active = 1
					current_user.role_id = @role.id
					current_user.subscription_id = @subscription.id
					current_user.save
					redirect_to root_path
				end
			end
		rescue Exception => e
			flash[:errors] = e.message
			redirect_to usersdir_v1_users_user_payments_path(current_user.id)
		end
	end

	def delete_card
		# cards = Stripe::Customer.retrieve("cus_BorNhUJ1kcGf1b").sources.all(object: :card)
		# cards.data.each do |card|
		# 	if card.fingerprint == params[""]
		# end
	end

	def add_new_card
		begin
			stripe_card = Stripe::Token.create( 
				:card => { 
					:number => params[:credit_card].to_s, 
					:exp_year => params[:expiry_date].split('-')[1].to_i, 
					:exp_month => params[:expiry_date].split('-')[0].to_i, 
					:cvc => params[:cvc].to_s,
					:name => params[:brand].to_s 
				} 
			)
			card = Card.find_by_fingerprint stripe_card.card.fingerprint
			if card.nil?
				Stripe::Customer.retrieve(current_user.customer_id).sources.create(source: stripe_card.id)
				card = Card.create( 
					stripe_id: stripe_card.id,
				 	user_id: current_user.id,
				 	last_4: stripe_card.card.last4, 
				 	fingerprint: stripe_card.card.fingerprint, 
				 	brand: stripe_card.card.brand, 
				 	exp_month: stripe_card.card.exp_month, 
				 	exp_year: stripe_card.card.exp_year, 
				 	is_active: 0, 
				 	card_name: stripe_card.card.name
				 )
			else
				flash[:error] = "This card already exists"
			end
			redirect_to usersdir_v1_users_profile_path(current_user.id)
		rescue Exception => e
			flash[:error] = e.message
			redirect_to usersdir_v1_users_profile_path(current_user.id)
		end
		
	end
end

app/controllers/usersdir/v1/users/registrations_controller.rb
class Usersdir::V1::Users::RegistrationsController < Devise::RegistrationsController
  def new
    super
  end

  def create
    super
  end
  
  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :subscription, :is_active, :email, :password, :password_confirmation)
  end
end

app/controllers/usersdir/v1/users/sessions_controller.rb
class Usersdir::V1::Users::SessionsController < Devise::SessionsController
   def new
     super
   end

   def create
   	 super
   end
end

app/controllers/usersdir/v1/users/users_controller.rb
class Usersdir::V1::Users::UsersController < ApplicationController
	before_action :complete_registration, except: [:incomplete]
	layout "users"
	def index
		@search_limit = ((Role.find(current_user.role_id)).total_search == (User.find(current_user.id)).search_count)
		@patches = Patch.where("user_id = ?", current_user.id)
	end
	def show
		@cards = current_user.cards.to_a
		@available = []
		@cards.each do |card|
			if card.is_active == true
				@active = card
			else
				@available.push card
			end
		end
		@searches = current_user.searches.select(:location_id, :full_name, :address, :city, :state, :zip, :phone).distinct
	end
	def clear_patches
		user_patches = current_user.patches
		user_patches.destroy_all
		render json: { destroyed: true }
	end
	def edit
		@role = Role.find(current_user.role_id)
	end
	def update_details
		if params[:commit] != "CANCEL"
			current_user.update_attributes user_params
			flash[:success] = "Succesfully updated Personal Info"
		end
		redirect_to edit_usersdir_v1_users_user_path(current_user.id)
	end

	def update_password
		if params[:commit] != "CANCEL"
			if current_user.update_with_password(pass_params)
				bypass_sign_in current_user
				flash[:success] = "Password successfully updated"
			else
				flash[:error] = "Password not saved"
			end
		end			
		redirect_to edit_usersdir_v1_users_user_path(current_user.id)
	end

	def update_subscription
		if params[:subscription][:role] != "#{params[:subscription][:sub_group].downcase}-#{params[:subscription][:sub_type].downcase}"
			subscription = Stripe::Subscription.retrieve(current_user.subscription_id)
			item_id = subscription.items.data[0].id
			items = [{
				id: item_id,
				plan: "#{params[:subscription][:sub_group].downcase}-#{params[:subscription][:sub_type].downcase}"
			}]
			subscription.items = items
			subscription.save

			role = Role.find_by_number("#{params[:subscription][:sub_group].downcase}-#{params[:subscription][:sub_type].downcase}")
			current_user.role_id =role.id
			current_user.save
		end
		redirect_to edit_usersdir_v1_users_user_path(current_user.id)
		
	end
	def exports
		@results = [[], [], []]
		if params[:sub_type].present?
			if params["sub_type"] == "Residential"
				vertices = JSON.parse(params[:geometry])
				geometry = [[]]
				vertices.each do |vertex|
					point = []
					vertex.to_a.each do |key, value|
						point.push value
					end
					geometry[0].push point
				end
				polygon = Polygon.from_coordinates(geometry ,4326)
				@patch = Patch.create(user_id: current_user.id, geometry: geometry, patch_type: "residential")
				locations = Location.all
				locations.each do |location|
					point = Point.from_x_y_z(location.location_point[0], location.location_point[1], 0)
					if polygon.contains_point? point
						Search.create(user_id: current_user.id, patch_id: @patch.id, full_name: location.full_name, address: location.address, city: location.city, state: location.state, zip: location.zip, phone: location.phone, location_point: location.location_point, location_id: location.id)
						@results[1].push location
					end
				end
				current_user.search_count.nil? ? current_user.search_count = 1 : current_user.search_count += 1
				current_user.save
				render json: { patch_id: @patch.id }
			else
				if params[:geometry].blank?
					business = {}
					if !params["city"].blank? && !params["state"].blank? && !params["zip"].blank? && !params["naics"].blank?
						business = Business.where("city = ? AND state = ? AND zip = ? AND naics = ?", params["city"], params["state"], params["zip"], params["naics"])
					elsif !params["city"] && !params["zip"] && !params["naics"]
						business = Business.where("city = ? AND zip = ? AND naics = ?", params["city"], params["zip"], params["naics"])
					elsif !params["state"] && !params["zip"] && !params["naics"]
						business = Business.where("state = ? AND zip = ? AND naics = ?", params["state"], params["zip"], params["naics"])
					elsif !params["city"] && !params["state"] && !params["zip"]
						business = Business.where("city = ? AND state = ? AND zip = ?", params["city"], params["state"], params["zip"])
					elsif !params["state"].blank? && !params["zip"].blank?
						business = Business.where("state = ? AND zip = ?", params["state"], params["zip"])
					elsif !params["state"].blank? && !params["naics"].blank?
						business = Business.where("state = ? AND naics = ?", params["state"], params["naics"])
					elsif !params["zip"].blank? && !params["naics"].blank?
						business = Business.where("naics = ? AND zip = ?", params["zip"], params["naics"])
					elsif !params["city"].blank? && !params["state"].blank?
						business = Business.where("city = ? AND state = ?", params["city"], params["state"])
					elsif !params["city"].blank? && !params["zip"].blank?
						business = Business.where("city = ? AND zip = ?", params["city"], params["zip"])
					elsif !params["city"].blank? && !params["naics"].blank?
						business = Business.where("city = ? AND naics = ?", params["city"], params["naics"])							
					elsif !params["state"].blank?
						business = Business.where("state = ?", params["state"])
					elsif !params["zip"].blank?
						business = Business.where("zip = ?", params["zip"])
					elsif !params["naics"].blank?
						business = Business.where("naics = ?", params["naics"])
					elsif !params["city"].blank?
						business = Business.where("city = ?", params["city"])
					end
					render json: business
				else
					vertices = JSON.parse(params[:geometry])
					geometry = [[]]
					vertices.each do |vertex|
						point = []
						vertex.to_a.each do |key, value|
							point.push value
						end
						geometry[0].push point
					end
					polygon = Polygon.from_coordinates(geometry ,4326)
					@patch = Patch.create(user_id: current_user.id, geometry: geometry, patch_type: "business")
					businesses = Business.all
					businesses.each do |business|
						point = Point.from_x_y_z(business.business_point[0], business.business_point[1], 0)
						if polygon.contains_point? point
							BusinessSearch.create(user_id: current_user.id, patch_id: @patch.id, business_name: business.business_name, business_owner: business.business_owner, phone_number: business.phone_number, address: business.address, city: business.city, state: business.state, zip: business.zip, revenue: business.revenue, no_of_employees: business.no_of_employees, start_of_business: business.start_of_business, latitude: business.latitude, longitude: business.longitude, business_point: business.business_point )
							@results[0].push business
						end
					end
					current_user.search_count.nil? ? current_user.search_count = 1 : current_user.search_count += 1
					current_user.save
					render json: { patch_id: @patch.id }
				end
			end
		elsif params[:patch_id].present? && !params[:filter].present?
			patch = Patch.find params[:patch_id]
			if patch.patch_type == "business"
				@results[0] = patch.business_searches
				@results[2] = { patch_id: patch.id }
				@results[2] = { patch_id: patch.id, rev_max: patch.business_searches.maximum(:revenue), rev_min: patch.business_searches.minimum(:revenue), no_of_employees_max: patch.business_searches.maximum(:no_of_employees), no_of_employees_min: patch.business_searches.minimum(:no_of_employees) }
			else
				@results[1] = patch.searches
				@results[2] = { patch_id: patch.id }
			end
		elsif params[:filter].present?
			@patch = Patch.find params["patch_id"]
			if @patch.patch_type == "business"
				if params["field"] == "employee"
					@results[0] = @patch.business_searches.where("no_of_employees BETWEEN  ? AND ?", params["min"], params["max"])
					@results[2] = { patch_id: @patch.id }
					@results[2] = { patch_id: @patch.id, rev_max: @patch.business_searches.maximum(:revenue), rev_min: @patch.business_searches.minimum(:revenue), no_of_employees_max: @patch.business_searches.maximum(:no_of_employees), no_of_employees_min: @patch.business_searches.minimum(:no_of_employees) }
				else
					@results[0] = @patch.business_searches.where("revenue BETWEEN  ? AND ?", params["min"], params["max"])
					@results[2] = { patch_id: @patch.id }
					@results[2] = { patch_id: @patch.id, rev_max: @patch.business_searches.maximum(:revenue), rev_min: @patch.business_searches.minimum(:revenue), no_of_employees_max: @patch.business_searches.maximum(:no_of_employees), no_of_employees_min: @patch.business_searches.minimum(:no_of_employees) }
				end
			end
		else
			@results[0] = current_user.business_searches.select(:business_name, :business_owner, :address, :city, :state, :zip, :phone_number, :revenue, :no_of_employees, :start_of_business).distinct
			@results[1] = current_user.searches.select(:location_id, :full_name, :address, :city, :state, :zip, :phone).distinct
		end
	end

	private
	  def complete_registration
	  	if current_user.is_active.zero?
	  		redirect_to usersdir_v1_users_user_payments_path(current_user.id)
	  	elsif current_user.is_active == 2
	  		sign_out current_user
	  		flash[:error] = "Account was deactivated"
	  		redirect_to root_path
  		end
	  end
	  def user_params
	  	params.require(:details).permit(:first_name, :last_name, :phone_number)
	  end
	  def pass_params
	  	params.require(:user).permit(:current_password, :password, :password_confirmation)
	  end
end

app/helpers/adminsdir/v1/admins/users_helper.rb
module Adminsdir::V1::Admins::UsersHelper
end

app/helpers/usersdir/v1/users/cards_helper.rb
module Usersdir::V1::Users::CardsHelper
end

app/helpers/usersdir/v1/users/users_helper.rb
module Usersdir::V1::Users::UsersHelper
end

app/views/usersdir/v1/users/users/edit.html.haml
= content_for :title, "ICurb | User Profile"
= content_for :asset, "../../../assets/logo-default.png"
%br/
.container-fluid
  - if !flash[:success].nil?
    %input#message{ type: :hidden, value: flash[:success] }
    %input#type{ type: :hidden, value: "success" }
    .col-md-12#alerts-container{ style: "margin-top: 20px;" }
  - if !flash[:error].nil?
    %input#message{ type: :hidden, value: flash[:error] }
    %input#type{ type: :hidden, value: "danger" }
    .col-md-12#alerts-container{ style: "margin-top: 20px;" }
  .row
    .col-md-12
      .col-md-3
        .portlet.light.profile-sidebar-portlet.bordered
          .profile-userpic
            %img.img-responsive{:alt => "", :src => "../../../assets/photo3.jpg"}/
          .profile-usertitle
            .profile-usertitle-name= "#{current_user.first_name.titleize} #{current_user.last_name.titleize}"
            .profile-usertitle-job= current_user.email
            .profile-usertitle-job= current_user.phone_number.nil? ? "-" : current_user.phone_number
          .profile-usermenu
            %ul.nav
              %li
                = link_to usersdir_v1_users_path(current_user.id) do
                  %i.icon-home
                  Overview
              %li.active
                = link_to edit_usersdir_v1_users_user_path(current_user.id) do
                  %i.icon-settings
                  Account Settings
      .col-md-9{ style: "padding: 0px;" }
        .col-md-12
          .portlet.light.bordered
            .portlet-title
              .caption.font-grey-mint
                %span.caption-subject.bold.uppercase Personal Info
            .portlet-body
              = form_for User.new, as: :details, url: usersdir_v1_users_edit_path(:details) do |f|
                .form-group
                  .input-group.col-md-6.col-md-offset-3
                    %span.input-group-addon
                      %i.fa.fa-envelope
                    = f.text_field :first_name, class: "form-control form-control-solid placeholder-no-fix", placeholder: "First Name", autocomplete: :off, value: current_user.first_name
                    / %input.form-control.form-control-solid.placeholder-no-fix{ placeholder: "First Name", type: :text, autocomplete: :off, value: current_user.first_name }
                .form-group
                  .input-group.col-md-6.col-md-offset-3
                    %span.input-group-addon
                      %i.fa.fa-envelope
                    = f.text_field :last_name, class: "form-control form-control-solid placeholder-no-fix", placeholder: "Last Name", autocomplete: :off, value: current_user.last_name
                    / %input.form-control.form-control-solid.placeholder-no-fix{ placeholder: "Last Name", type: :text, autocomplete: :off, value: current_user.last_name }
                .form-group
                  .input-group.col-md-6.col-md-offset-3
                    %span.input-group-addon
                      %i.fa.fa-envelope
                    = f.text_field :phone_number, class: "form-control form-control-solid placeholder-no-fix", placeholder: "Phone Number", autocomplete: :off, value: current_user.phone_number
                    / %input.form-control.form-control-solid.placeholder-no-fix{ placeholder: "Phone Number", type: :text, autocomplete: :off, value: current_user.phone_number }
                .form-group
                  .input-group.col-md-6.col-md-offset-3
                    .col-md-3{ style: "padding-left: 0px;" }
                      = f.submit "SAVE CHANGES", class: "btn blue uppercase col-md-12"
                      / %button.btn.blue.uppercase.col-md-12 SAVE CHANGES
                    .col-md-3{ style: "padding-left: 0px;" }
                      = f.submit "CANCEL", class: "btn blue uppercase col-md-12"
                      / %button.btn.blue.uppercase.col-md-12 CANCEL
        .col-md-12
          .portlet.light.bordered
            .portlet-title
              .caption.font-grey-mint
                %span.caption-subject.bold.uppercase Upload Image
            .portlet-body
              = form_for User.new, as: :details, url: usersdir_v1_users_edit_path(:details) do |f|
                .form-group
                  .input-group.col-md-6.col-md-offset-3
                    %input{ type: :file }
                .form-group
                  .input-group.col-md-6.col-md-offset-3
                    .col-md-3{ style: "padding-left: 0px;" }
                      = f.submit "SAVE CHANGES", class: "btn blue uppercase col-md-12"
                      / %button.btn.blue.uppercase.col-md-12 SAVE CHANGES
                    .col-md-3{ style: "padding-left: 0px;" }
                      = f.submit "CANCEL", class: "btn blue uppercase col-md-12"
                      / %button.btn.blue.uppercase.col-md-12 CANCEL
        .col-md-12
          .portlet.light.bordered
            .portlet-title
              .caption.font-grey-mint
                %span.caption-subject.bold.uppercase Change Password
            .portlet-body
              = form_for current_user, url: update_password_path do |f|
                .form-group
                  .input-group.col-md-6.col-md-offset-3
                    %span.input-group-addon
                      %i.fa.fa-envelope
                    = f.password_field :current_password, class: "form-control form-control-solid placeholder-no-fix", placeholder: "Current Password", autocomplete: :off
                .form-group
                  .input-group.col-md-6.col-md-offset-3
                    %span.input-group-addon
                      %i.fa.fa-envelope
                    = f.password_field :password, class: "form-control form-control-solid placeholder-no-fix", placeholder: "New Password", autocomplete: :off
                .form-group
                  .input-group.col-md-6.col-md-offset-3
                    %span.input-group-addon
                      %i.fa.fa-envelope
                    = f.password_field :password_confirmation, class: "form-control form-control-solid placeholder-no-fix", placeholder: "Confirm Password", autocomplete: :off
                .form-group
                  .input-group.col-md-6.col-md-offset-3
                    .col-md-4{ style: "padding-left: 0px;" }
                      = f.submit "CHANGE PASSWORD", class: "btn blue uppercase col-md-12"
                    .col-md-3{ style: "padding-left: 0px;" }
                      = f.submit "CANCEL", class: "btn blue uppercase col-md-12"
        .col-md-12
          .portlet.light.bordered
            .portlet-title
              .caption.font-grey-mint
                %span.caption-subject.bold.uppercase SUBSCRIPTION
            .portlet-body
              = form_for :subscription, as: :subscription, url: update_subscription_path(:subscription) do |f|
                = f.hidden_field :role, value: @role.number
                .form-group
                  .input-group.col-md-6.col-md-offset-3
                    = f.select(:sub_group, options_for_select([ "Individual", "Business" ], :selected => @role.number.split('-')[0].to_s == 'business' ? "Business" : "Individual" ), {}, { class: "bs-select form-control" })
                .form-group
                  .input-group.col-md-6.col-md-offset-3
                    = f.select(:sub_type, options_for_select( [ "Average", "OK", "Premium"], :selected => @role.number.split('-')[1].to_s == 'bronze' ? 'Average' : (@role.number.split('-')[1].to_s == 'silver' ? "OK" : "Premium") ), {}, class: "bs-select form-control" )
                .form-group
                  .input-group.col-md-6.col-md-offset-3
                    .col-md-4{ style: "padding-left: 0px;" }
                      = f.submit "CHANGE SUBSCRIPTION", class: "btn blue uppercase col-md-12"
                    .col-md-3{ style: "padding-left: 0px;" }
                      = f.submit "CANCEL", class: "btn blue uppercase col-md-12"