config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'adminsdir', controllers: {
    registrations: "adminsdir/v1/admins/registrations",
    sessions: "adminsdir/v1/admins/sessions"
    }, path_names: { sign_in: :login }

  devise_scope :admin do
    post 'adminsdir/add_admin' => "adminsdir/v1/admins/registrations#add_admin", as: :adminsdir_v1_admins_new_admin
  end  
  
  devise_for :users, path: '' , controllers: {
    registrations: "usersdir/v1/users/registrations",
    sessions: "usersdir/v1/users/sessions"
    }, path_names: { sign_up: :register }

  authenticated :admin do
    root "adminsdir/v1/admins/admins#index", as: :admin_authenticated_root
  end

  authenticated :user do
    root 'usersdir/v1/users/users#index', as: :authenticated_root
  end
  namespace :adminsdir do
    namespace :v1, path: '' do
      namespace :admins, path: '' do
        get 'add_admin' => "admins#new_admin"
        root 'admins#index'
        resources :users
        get 'change_status' => "users#change_status"
        get 'admin_change_status' => "admins#change_status"
        get "profile" => "admins#profile"
        post 'update_details' => "admins#update_details"
        patch 'update_password' => "admins#update_password"
        resources :admins

      end
    end
  end
  post 'new_card' => 'usersdir/v1/users/cards#add_new_card'
  patch 'update_password' => "usersdir/v1/users/users"
  post 'update_subscription' => "usersdir/v1/users/users#update_subscription"
  namespace :usersdir, path: '' do
    namespace :v1, path: '' do
      namespace :users, path: '' do
        get 'profile/:id' => 'users#show'
        post 'edit' => 'users#update_details'
        post 'exports' => 'users#exports'
        get 'exports' => 'users#exports'
        post 'filter_export' => 'users#filter_export'
        post 'clear_patches' => "users#clear_patches"
        resources :users, except: [:show] do
          get 'payments' => 'cards#new'
          resources :cards, except: [:new]
        end
      end
    end
  end

  
  get 'addpin' => 'welcome#addpin'
  get 'test' => 'welcome#stripetest'
  get 'pricing' => 'welcome#pricing'

  root 'welcome#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/business.rb
class Business < ActiveRecord::Base
end

app/models/business_search.rb
class BusinessSearch < ActiveRecord::Base
	belongs_to :user
	belongs_to :patch
end

app/models/card.rb
class Card < ActiveRecord::Base
	belongs_to :user
end

app/models/county.rb
require 'memoist'

class County < ActiveRecord::Base
  extend Memoist
  belongs_to :state
  has_many :zipcodes

  validates :name, uniqueness: { scope: :state_id, case_sensitive: false },
                   presence: true

  scope :without_zipcodes, -> { joins("LEFT JOIN zipcodes ON zipcodes.county_id = counties.id").where("zipcodes.county_id IS NULL") }
  scope :without_state, -> { where("state_id IS NULL") }

  def cities
    zipcodes.map(&:city).sort.uniq
  end
  memoize :cities
end

app/models/location.rb
class Location < ActiveRecord::Base
	def self.add_location
		
	end
	def self.update_location
		
	end
end

app/models/log.rb
class Log < ActiveRecord::Base
end

app/models/patch.rb
class Patch < ActiveRecord::Base
	belongs_to :user
	has_many :searches
	has_many :business_searches
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/search.rb
class Search < ActiveRecord::Base
	belongs_to :user
	belongs_to :patch
end

app/models/state.rb
require 'memoist'

class State < ActiveRecord::Base
  extend Memoist
  has_many :zipcodes
  has_many :counties

  validates :abbr, uniqueness: { case_sensitive: false }, presence: true
  validates :name, uniqueness: { case_sensitive: false }, presence: true

  def cities
    zipcodes.map(&:city).sort.uniq
  end
  memoize :cities
  
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_create :generate_customer_id
  has_many :cards
  has_many :patches
  has_many :searches
  has_many :business_searches
 private
	def generate_customer_id
		customer = Stripe::Customer.create(:email => self.email)
		self.customer_id = customer.id
		self.save
	end
end

app/models/zipcode.rb
class Zipcode < ActiveRecord::Base
  belongs_to :county
  belongs_to :state

  validates :code, uniqueness: true, presence: true
  validates :state_id, :county_id, :city, presence: true

  scope :without_county, -> { where("county_id IS NULL") }
  scope :without_state, -> { where("state_id IS NULL") }
  scope :ungeocoded, -> { where("lat IS NULL OR lon IS NULL") }

  class << self
    def find_by_city_state(city, state)
      includes(county: :state)
        .where("city like ? AND states.abbr like ?", "#{city}%", "%#{state}%")
        .first
    end
  end

  def latlon
    [lat, lon]
  end

  def geocoded?
    (!lat.nil? && !lon.nil?)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
  # before_filter :force_www!

  private
    def force_www!
      if request.host[0..3] != "www." && Rails.env != "development" && request.host[0..3] != "172"
        redirect_to "#{request.protocol}www.#{request.host_with_port}#{request.fullpath}", :status => 301
      end
    end

    # Overwriting the sign_out redirect path method
    def after_sign_out_path_for(resource_or_scope)
      if resource_or_scope == :user
        root_path
      else
        adminsdir_v1_admins_root_path
      end
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
    # Stripe::Plan.create(amount: 9700, interval: :month, name: "Individual Bronze", currency: :usd, id: "individual-bronze")
    # Stripe::Plan.create(amount: 12500, interval: :month, name: "Individual Silver", currency: :usd, id: "individual-silver")
    # Stripe::Plan.create(amount: 19700, interval: :month, name: "Individual Gold", currency: :usd, id: "individual-gold")
    # Stripe::Plan.create(amount: 39700, interval: :month, name: "Business Bronze", currency: :usd, id: "business-bronze")
    # Stripe::Plan.create(amount: 69700, interval: :month, name: "Business Silver", currency: :usd, id: "business-silver")
    # Stripe::Plan.create(amount: 99700, interval: :month, name: "Business Gold", currency: :usd, id: "business-gold")
  end

  def pricing
  	roles = Role.all
  	@individual = []
  	@business = []
  	roles.each do |role|
  		if role.name.include? "Individual"
  			@individual.push role
  		else
  			@business.push role
  		end
  	end
  end

  def stripetest
    # link = "https://search.onboard-apis.com/poisearch/v2.0.0/poi/geography?PostalCodeKey=99811&SearchDistance=10000&RecordLimit=100"
    # @homeowner = JSON.parse(RestClient.get(link, headers = { Accept: :json, apikey: "9d078487e223b1c4d54c3f3a3f628803" }))
    # render json: @homeowner
  end





  def addpin
    
  end
end

app/helpers/adminsdir/v1/admins/users_helper.rb
module Adminsdir::V1::Admins::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def javascript_include_action_specific_js
		javascript_include_tag "#{controller.controller_path.tr("/","_")}_#{controller.action_name}" if (File.exists?("#{Rails.root}/app/assets/javascripts/#{controller.controller_path.tr("/","_")}_#{controller.action_name}.js") || File.exists?("#{Rails.root}/app/assets/javascripts/#{controller.controller_path.tr("/","_")}_#{controller.action_name}.js.coffee"))
	end
end

app/helpers/usersdir/v1/users/cards_helper.rb
module Usersdir::V1::Users::CardsHelper
end

app/helpers/usersdir/v1/users/users_helper.rb
module Usersdir::V1::Users::UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/adminsdir/v1/admins/admins/new_admin.html.haml
.content-fluid
  .row
    .col-md-4.col-md-offset-4
      %div{:class => "col-md-10.col-md-offset-1"}
        .portlet.light
          .portlet-body{:style => "padding-bottom: 30px;"}
            %br/
            = form_for(Admin.new, as: :admin, url: adminsdir_v1_admins_new_admin_path(:admin), :html => { class: "login-form" }) do |f|
              .form-group
                = f.text_field :first_name, autofocus: true, class: "form-control form-control-solid placeholder-no-fix", placeholder: "First Name"
              .form-group
                = f.text_field :last_name, autofocus: true, class: "form-control form-control-solid placeholder-no-fix", placeholder: "Last Name"
              .form-group
                = f.email_field :email, autofocus: true, class: "form-control form-control-solid placeholder-no-fix", placeholder: "Email Address"
              .form-group
                = f.password_field :password, autocomplete: "off", class: "form-control form-control-solid placeholder-no-fix", placeholder: "Password"
                = f.hidden_field :is_active, value: 1
              %br/
              .form-action{:style => "text-align:center;"}
                = f.submit "Log in", class: "btn green uppercase"

app/views/adminsdir/v1/admins/admins/profile.html.haml
= content_for :title, "ICurb | User Profile"
= content_for :asset, "../../../assets/logo-default.png"
%br/
.container-fluid
  - if !flash[:success].nil?
    %input#message{ type: :hidden, value: flash[:success] }
    %input#type{ type: :hidden, value: "success" }
    .col-md-12#alerts-container{ style: "margin-top: 20px;" }
  - if !flash[:error].nil?
    %input#message{ type: :hidden, value: flash[:error] }
    %input#type{ type: :hidden, value: "danger" }
    .col-md-12#alerts-container{ style: "margin-top: 20px;" }
  .row
    %br/
    .col-md-12
      .col-md-3
        .portlet.light.profile-sidebar-portlet.bordered
          .profile-userpic
            %img.img-responsive{:alt => "", :src => "../../../assets/photo3.jpg"}/
          .profile-usertitle
            .profile-usertitle-name= "#{current_admin.first_name} #{current_admin.last_name}"
            .profile-usertitle-job= current_admin.email
            .profile-usertitle-job= current_admin.phone_number.nil? ? "-" : current_admin.phone_number
          .profile-usermenu
      .col-md-9{ style: "padding: 0px;" }
        .col-md-12
          .portlet.light.bordered
            .portlet-title
              .caption.font-grey-mint
                %span.caption-subject.bold.uppercase Personal Info
            .portlet-body
              = form_for Admin.new, as: :details, url: adminsdir_v1_admins_update_details_path(:details) do |f|
                .form-group
                  .input-group.col-md-6.col-md-offset-3
                    %span.input-group-addon
                      %i.fa.fa-envelope
                    = f.text_field :first_name, class: "form-control form-control-solid placeholder-no-fix", placeholder: "First Name", autocomplete: :off, value: current_admin.first_name
                .form-group
                  .input-group.col-md-6.col-md-offset-3
                    %span.input-group-addon
                      %i.fa.fa-envelope
                    = f.text_field :last_name, class: "form-control form-control-solid placeholder-no-fix", placeholder: "Last Name", autocomplete: :off, value: current_admin.last_name
                .form-group
                  .input-group.col-md-6.col-md-offset-3
                    %span.input-group-addon
                      %i.fa.fa-envelope
                    = f.text_field :phone_number, class: "form-control form-control-solid placeholder-no-fix", placeholder: "Phone Number", autocomplete: :off, value: current_admin.phone_number
                .form-group
                  .input-group.col-md-6.col-md-offset-3
                    .col-md-3{ style: "padding-left: 0px;" }
                      = f.submit "SAVE CHANGES", class: "btn blue uppercase col-md-12"
                    .col-md-3{ style: "padding-left: 0px;" }
                      = f.submit "CANCEL", class: "btn blue uppercase col-md-12"
                

        .col-md-12
          .portlet.light.bordered
            .portlet-title
              .caption.font-grey-mint
                %span.caption-subject.bold.uppercase Change Password
            .portlet-body
              = form_for current_admin, url: adminsdir_v1_admins_update_password_path do |f|
                .form-group
                  .input-group.col-md-6.col-md-offset-3
                    %span.input-group-addon
                      %i.fa.fa-envelope
                    = f.password_field :current_password, class: "form-control form-control-solid placeholder-no-fix", placeholder: "Current Password", autocomplete: :off
                .form-group
                  .input-group.col-md-6.col-md-offset-3
                    %span.input-group-addon
                      %i.fa.fa-envelope
                    = f.password_field :password, class: "form-control form-control-solid placeholder-no-fix", placeholder: "New Password", autocomplete: :off
                .form-group
                  .input-group.col-md-6.col-md-offset-3
                    %span.input-group-addon
                      %i.fa.fa-envelope
                    = f.password_field :password_confirmation, class: "form-control form-control-solid placeholder-no-fix", placeholder: "Confirm Password", autocomplete: :off
                .form-group
                  .input-group.col-md-6.col-md-offset-3
                    .col-md-4{ style: "padding-left: 0px;" }
                      = f.submit "CHANGE PASSWORD", class: "btn blue uppercase col-md-12"
                    .col-md-3{ style: "padding-left: 0px;" }
                      = f.submit "CANCEL", class: "btn blue uppercase col-md-12"

app/views/adminsdir/v1/admins/admins/show.html.haml
= content_for :title, "ICurb | User Profile"
= content_for :asset, "../../../assets/logo-default.png"
%br/
.container-fluid
  - if !flash[:success].nil?
    %input#message{ type: :hidden, value: flash[:success] }
    %input#type{ type: :hidden, value: "success" }
    .col-md-12#alerts-container{ style: "margin-top: 20px;" }
  - if !flash[:error].nil?
    %input#message{ type: :hidden, value: flash[:error] }
    %input#type{ type: :hidden, value: "danger" }
    .col-md-12#alerts-container{ style: "margin-top: 20px;" }
  .row
    .col-md-12
      .col-md-12
        = link_to root_path do
          %button.btn.btn-outline.green BACK
    %br/
    %br/
    .col-md-12
      .col-md-3
        .portlet.light.profile-sidebar-portlet.bordered
          .profile-userpic
            %img.img-responsive{:alt => "", :src => "../../../assets/photo3.jpg"}/
          .profile-usertitle
            .profile-usertitle-name= "#{@admin.first_name} #{@admin.last_name}"
            .profile-usertitle-job= @admin.email
            .profile-usertitle-job= @admin.phone_number.nil? ? "-" : @admin.phone_number
            %br/
            - if @admin.is_active == 1
              = link_to adminsdir_v1_admins_admin_change_status_path(status: 0, id: params[:id]) do
                %button.btn.btn-outline.btn-circle.red DEACTIVATE ACCOUNT
            - else
              = link_to adminsdir_v1_admins_admin_change_status_path(status: 1, id: params[:id]) do
                %button.btn.btn-outline.btn-circle.green ACTIVATE ACCOUNT
          .profile-usermenu
      .col-md-9{ style: "padding: 0px;" }
        .col-md-12
          .portlet.light.bordered
            .portlet-title
              .caption.font-grey-mint
                %span.caption-subject.bold.uppercase Personal Info
            .portlet-body
              %form
                .form-group
                  .input-group.col-md-6.col-md-offset-3
                    %span.input-group-addon
                      %i.fa.fa-envelope
                    / # = f.text_field :first_name, class: "form-control form-control-solid placeholder-no-fix", placeholder: "First Name", autocomplete: :off, value: current_user.first_name
                    %input.form-control.form-control-solid.placeholder-no-fix{ placeholder: "First Name", type: :text, autocomplete: :off, value: @admin.first_name }
                .form-group
                  .input-group.col-md-6.col-md-offset-3
                    %span.input-group-addon
                      %i.fa.fa-envelope
                    / # = f.text_field :last_name, class: "form-control form-control-solid placeholder-no-fix", placeholder: "Last Name", autocomplete: :off, value: current_user.last_name
                    %input.form-control.form-control-solid.placeholder-no-fix{ placeholder: "Last Name", type: :text, autocomplete: :off, value: @admin.last_name }
                .form-group
                  .input-group.col-md-6.col-md-offset-3
                    %span.input-group-addon
                      %i.fa.fa-envelope
                    / # = f.text_field :phone_number, class: "form-control form-control-solid placeholder-no-fix", placeholder: "Phone Number", autocomplete: :off, value: current_user.phone_number
                    %input.form-control.form-control-solid.placeholder-no-fix{ placeholder: "Phone Number", type: :text, autocomplete: :off, value: @admin.phone_number }
                .form-group
                  .input-group.col-md-6.col-md-offset-3
                    .col-md-3{ style: "padding-left: 0px;" }
                      / # = f.submit "SAVE CHANGES", class: "btn blue uppercase col-md-12"
                      %button.btn.blue.uppercase.col-md-12 SAVE CHANGES
                    .col-md-3{ style: "padding-left: 0px;" }
                      / # = f.submit "CANCEL", class: "btn blue uppercase col-md-12"
                      %button.btn.blue.uppercase.col-md-12 CANCEL
                

        .col-md-12
          .portlet.light.bordered
            .portlet-title
              .caption.font-grey-mint
                %span.caption-subject.bold.uppercase Change Password
            .portlet-body
              / = form_for current_user, url: update_password_path do |f|
              %form
                .form-group
                  .input-group.col-md-6.col-md-offset-3
                    %span.input-group-addon
                      %i.fa.fa-envelope
                    %input.form-control.form-control-solid.placeholder-no-fix{ placeholder: "Current User" }
                    / # = f.password_field :current_password, class: "form-control form-control-solid placeholder-no-fix", placeholder: "Current Password", autocomplete: :off
                .form-group
                  .input-group.col-md-6.col-md-offset-3
                    %span.input-group-addon
                      %i.fa.fa-envelope
                    %input.form-control.form-control-solid.placeholder-no-fix{ placeholder: "Current User" }
                    / # = f.password_field :password, class: "form-control form-control-solid placeholder-no-fix", placeholder: "New Password", autocomplete: :off
                .form-group
                  .input-group.col-md-6.col-md-offset-3
                    %span.input-group-addon
                      %i.fa.fa-envelope
                    %input.form-control.form-control-solid.placeholder-no-fix{ placeholder: "Current User" }
                    / # = f.password_field :password_confirmation, class: "form-control form-control-solid placeholder-no-fix", placeholder: "Confirm Password", autocomplete: :off
                .form-group
                  .input-group.col-md-6.col-md-offset-3
                    .col-md-4{ style: "padding-left: 0px;" }
                      / # = f.submit "CHANGE PASSWORD", class: "btn blue uppercase col-md-12"
                      %button.btn.blue.uppercase.col-md-12 CHANGE PASSWORD
                    .col-md-3{ style: "padding-left: 0px;" }
                      %button.btn.blue.uppercase.col-md-12 CANCEL
                      / # = f.submit "CANCEL", class: "btn blue uppercase col-md-12"

app/views/adminsdir/v1/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/admin.html.haml
!!!
%html{lang: "en"}
  %head
    %title= yield(:title)

    %meta{ charset: "utf-8"}/
    %meta{ content: "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{ content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0", :name => "viewport"}/
    %meta{ content: "width=device-width", :name => "viewport"}/
    %meta{ content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/

    = stylesheet_link_tag "application", media: :all
    %link{:crossorigin => "anonymous", :href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", :integrity => "sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN", :rel => "stylesheet"}/
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css", :rel => "stylesheet"}/
    %link{ href: "http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all", rel: "stylesheet", type: "text/css"}/
    %link{ href: "", rel: "shortcut icon", type: "image/x-icon"}/
    = csrf_meta_tags

  - if admin_signed_in?
    %body.page-container-bg-solid
      .page-wrapper-top
        .page-header.page-header-extension
          .page-header-top
            .container-fluid{ style: "background-color: white;" }
              .page-logo
                = link_to adminsdir_v1_admins_root_path do
                  %img.logo-default{ src: "#{ content_for?(:asset) == false ? "../assets/logo-default.png" : yield(:asset) }", alt: :logo, style: "width:100px;margin-top:5px;" }
              .top-menu
                %ul.nav.navbar-nav.pull-right
                  %li.navbar-links
                    = link_to adminsdir_v1_admins_root_path do
                      %i.fa.fa-home
                      HOME
                  %li.navbar-links
                    = link_to adminsdir_v1_admins_profile_path do
                      %i.fa.fa-user
                      PROFILE
                  %li.navbar-links
                    = link_to destroy_admin_session_path, method: :delete do
                      %i.fa.fa-sign-out
                      LOGOUT
          = yield
  - else
    %body.page-container-bg-solid{ style: "background-color: #32c5d2;" }
      = render "adminsdir/v1/admins/sessions/new"
  = javascript_include_tag controller_name if File.exists?("#{Rails.root}/app/assets/javascripts/#{controller_name}.js")
  = javascript_include_action_specific_js

  = javascript_include_tag "application", "data-turbolinks-track" => true
  = yield(:javascripts)

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %title= yield(:title)

    %meta{ charset: "utf-8"}/
    %meta{ content: "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{ content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0", :name => "viewport"}/
    %meta{ content: "width=device-width", :name => "viewport"}/
    %meta{ content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %link{ href: "../assets/logo_default.png", rel: :icon }
    = stylesheet_link_tag "application", media: :all
    %link{:crossorigin => "anonymous", :href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", :integrity => "sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN", :rel => "stylesheet"}/
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css", :rel => "stylesheet"}/
    %link{ href: "http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all", rel: "stylesheet", type: "text/css"}/
    %link{ href: "", rel: "shortcut icon", type: "image/x-icon"}/
    = csrf_meta_tags

  %body.page-container-bg-solid
    .page-wrapper-top
      .page-header.page-header-extension
        .page-header-top
          .container-fluid{ style: "background-color: transparent;" }
            .page-logo
              = link_to root_path do
                %img.logo-default{ src: "#{ content_for?(:asset) == false ? "/assets/logo-default.png" : yield(:asset) }", alt: :logo, style: "width:100px;margin-top:5px;" }
            .top-menu
              %ul.nav.navbar-nav.pull-right
                %li.navbar-links
                  %a HOME
                %li.navbar-links
                  %a MEDIA
                %li.navbar-links
                  = link_to pricing_path do
                    PRICING
                %li.navbar-links
                  %a BLOG
                %li.navbar-links
                  %a FAQ
                %li.navbar-links
                  %a ABOUT US
                %li.navbar-links
                  %a{ href: "#basic", "data-toggle" => :modal }
                    %span LOGIN
                %li.navbar-links
                  = link_to pricing_path do
                    %span SIGN UP
        - if !user_signed_in?
          - flash.each do |key, value|
            - if key == "notice"
              %input#message{ type: :hidden, value: value }
              %input#type{ type: :hidden, value: "success" }
            - else
              %input#message{ type: :hidden, value: value }
              %input#type{ type: :hidden, value: "danger" }
              .col-md-12#alerts-container{ style: "margin-top: 20px;" }
        = yield
    .modal.fade#basic{ tabindex: -1, role: :basic, "aria-hidden" => true }
      %br/
      %br/
      %br/
      %center
        .modal-dialog{ style: "width: 480px;" }
          .modal-content
            .modal-header
              %button.close{ "aria-hidden" => true, "data-dismiss" => :modal, type: :button}
              %h4{ align: :center } SIGN IN
            .modal-body
              .row
                .col-md-12
                  %br
                  .content
                    %center
                      = render "usersdir/v1/users/sessions/new"
                      %br/
                    
    = javascript_include_tag controller_name if File.exists?("#{Rails.root}/app/assets/javascripts/#{controller_name}.js")
    = javascript_include_action_specific_js

    = javascript_include_tag "application", "data-turbolinks-track" => true
    = yield(:javascripts)